<?php

namespace ShopBundle\Repository;

/**
 * btwRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class btwRepository extends \Doctrine\ORM\EntityRepository
{
}
