<?php

namespace ShopBundle\Repository;

/**
 * factuur_regelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class factuur_regelRepository extends \Doctrine\ORM\EntityRepository
{
}
