<?php

namespace ShopBundle\Repository;

/**
 * factuurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class factuurRepository extends \Doctrine\ORM\EntityRepository
{
}
