<?php

namespace ShopBundle\Repository;

/**
 * staffeltredeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class staffeltredeRepository extends \Doctrine\ORM\EntityRepository
{
}
