<?php

namespace ShopBundle\Repository;

/**
 * staffelgroepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class staffelgroepRepository extends \Doctrine\ORM\EntityRepository
{
}
